// <auto-generated />
namespace TorneioTabajara.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Reestruturando_Codigo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Reestruturando_Codigo));
        
        string IMigrationMetadata.Id
        {
            get { return "202504182009107_Reestruturando_Codigo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
